name: Unit Tests

on:
  workflow_call:
    package_path:
      required: true
      type: string

jobs:
  mocha:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve Prepared Repository
        uses: actions/download-artifact@v2
        with:
          name: setup-app

      - name: Unzip Artifact
        run: unzip app.zip

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"
          
      - name: Install Mocha
        run: yarn global add mocha

      - name: Run Mocha
        id: mocha_run
        run: mocha --package ${{ inputs.package_path }} --check-leaks --reporter spec --recursive --exit
